const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('skinmatch', {
  getState: () => ipcRenderer.invoke('getState'),
  onState: (cb) => ipcRenderer.on('state', (_e, s) => cb(s)),
  applySkin: (id) => ipcRenderer.invoke('applySkin', id),
  refresh: () => ipcRenderer.invoke('refresh'),
  setSettings: (patch) => ipcRenderer.invoke('setSettings', patch),
  champions: () => ipcRenderer.invoke('champions'),
  explore: (a, f, b) => ipcRenderer.invoke('explore', a, f, b),
  sharedLines: () => ipcRenderer.invoke('sharedLines'),
  hideOverlay: () => ipcRenderer.invoke('hideOverlay'),
  myIp: () => ipcRenderer.invoke('myIp'),
  stats: (who, mode, friend) => ipcRenderer.invoke('stats', who, mode, friend),
  addFriend: (puuid) => ipcRenderer.invoke('addFriend', puuid),
  removeFriend: (puuid) => ipcRenderer.invoke('removeFriend', puuid),
  addAddress: (address) => ipcRenderer.invoke('addAddress', address),
  collection: () => ipcRenderer.invoke('collection'),
  profiles: () => ipcRenderer.invoke('profiles'),
  profile: (puuid, limit) => ipcRenderer.invoke('profile', puuid, limit),
  matchDetail: (gameId, puuid) => ipcRenderer.invoke('matchDetail', gameId, puuid),
  refreshProfile: (puuid) => ipcRenderer.invoke('refreshProfile', puuid),
  addRiotId: (id) => ipcRenderer.invoke('addRiotId', id),
  lookupRiotId: (id) => ipcRenderer.invoke('lookupRiotId', id),
  addFriendPuuid: (puuid) => ipcRenderer.invoke('addFriendPuuid', puuid),
  friends: () => ipcRenderer.invoke('friends'),
  installUpdate: () => ipcRenderer.invoke('installUpdate'),
  checkForUpdates: () => ipcRenderer.invoke('checkForUpdates'),
  authSend: (email) => ipcRenderer.invoke('authSend', email),
  authVerify: (email, code) => ipcRenderer.invoke('authVerify', email, code),
  authSignOut: () => ipcRenderer.invoke('authSignOut'),
  removeWatch: (puuid) => ipcRenderer.invoke('removeWatch', puuid),
  saveKey: (key) => ipcRenderer.invoke('saveKey', key),
  partySummary: (puuids) => ipcRenderer.invoke('partySummary', puuids),
  championDetail: (id) => ipcRenderer.invoke('championDetail', id),
  startImport: (key) => ipcRenderer.invoke('startImport', key),
  stopImport: () => ipcRenderer.invoke('stopImport'),
});
